Add sns publish
LBHackney-IT/account-api pull request #31
Opened 2021-09-09 15:09 UTC by LBHSPreston

## Link to JIRA ticket
https://app.clickup.com/t/1dfp86u

## Describe this PR
This PR links successful account creation or update to the account SNS topic.

### *What is the problem we're trying to solve*
This allows notifications to be published when account entities are created or changed.

### *What changes have we introduced*
add method calls to the create and update use cases to call the SNS gateway and publish events

#### _Checklist_
- [x] Added tests to cover all new production code
- [x] Checked all code for possible refactoring
- [x] Code pipeline builds correctly

2021-09-09 15:57 UTC, sandipchandra approved these changes
Approved

2021-09-09 16:38 UTC, HHjolany requested changes

2021-09-09 16:38 UTC, HHjolany commented on AccountsApi.Tests/AwsIntegrationTests.cs
> +            new TableDef { Name = "Accounts", KeyName = "id", KeyType = ScalarAttributeType.S }
because of some global secondary index we need to pass the indexes too
i changed the TableDef and DynamoDbMockWebApplicationFactory
would you please take a look 
in the development branch

thank you

2021-09-10 10:54 UTC, HHjolany approved these changes

2021-09-20 08:13 UTC, merged