Dev
LBHackney-IT/account-api pull request #7
Opened 2021-08-09 09:19 UTC by hamidjolany

## Link to JIRA ticket

Add a link to the JIRA ticket that the changes in this PR describe.

## Describe this PR

### *What is the problem we're trying to solve*

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.

### *What changes have we introduced*

Add descriptions of what changes were made to address the problem and provide a solution.

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2021-08-11 07:25 UTC, LBHSPreston commented on AccountsApi.Tests/V1/Factories/EntityFactoryTest.cs
> +                Id = Guid.Parse("82aa6932-e98d-41a1-a4d4-2b44135554f8"),
These tests need to be a bit more dynamic, either using trangulation or dynamically generated fake data

2021-08-11 07:27 UTC, LBHSPreston commented on AccountsApi.Tests/V1/Infrastructure/DynamoDbInitilisationExtensionsTests.cs
> +        [Theory]
This is a good example of triangulated tests as per my previous comment.  Maybe a bit more of this.

2021-08-11 07:35 UTC, LBHSPreston commented on AccountsApi/Startup.cs
> +        private const string ApiName = "AccountAPI";
This should be pluralised as per our namespace?

2021-08-11 07:38 UTC, LBHSPreston commented on AccountsApi/V1/Controllers/AccountApiController.cs
> +        /// Get a list of Arrear Account models
Should be arrears instead of arrear.

2021-08-11 07:39 UTC, LBHSPreston commented on AccountsApi/V1/Domain/ConsolidatedCharges.cs
> +    public class ConsolidatedCharge
Should be ConsolidatedCharges.  There would probably not be a need to consolidate if there is only one charge.

2021-08-11 07:53 UTC, LBHSPreston requested changes
Quite a hefty pull request.  Moving forward we really need to break these down into more manageable chunks.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Domain/Enum.cs
> +        Estate, Block, Core, Flat
We may need to revisit this.  Do we know if these hardcoded enums will ever change?  This might have to be  a configurable item or a reference lookup.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Domain/Enum.cs
>          Active, Suspended, Ended
We may need to revisit this.  Do we know if these hardcoded enums will ever change?  This might have to be  a configurable item or a reference lookup.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Domain/Enum.cs
> +    public enum Title
We may need to revisit this.  Do we know if these hardcoded enums will ever change?  This might have to be  a configurable item or a reference lookup.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Domain/Enum.cs
> +    public enum AccountType
We may need to revisit this.  Do we know if these hardcoded enums will ever change?  This might have to be  a configurable item or a reference lookup.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Domain/Enum.cs
> +    public enum RentGroupType
We may need to revisit this.  Do we know if these hardcoded enums will ever change?  This might have to be  a configurable item or a reference lookup.  There is a reference lookups API we can probably reuse for this.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Factories/EntityFactory.cs
> +                RentGroupType = account.RentGroupType,
Possible null reference exception?  Might be a good idea to check for null for these complex objects from a different source.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Gateways/DynamoDbGateway.cs
> +            ScanCondition scanConditionTargetId = new ScanCondition("TargetId", ScanOperator.Equal, targetId);
We need to evaluate the use of scans on our DynamoDb tables, particularly where we are filtering on more than one property or index, it is a very expensive operation and generally not good practice.  We can consider using query vs scan operations or look for an alternative way of querying our DynamoDb tables.

2021-08-11 07:53 UTC, LBHSPreston commented on AccountsApi/V1/Gateways/DynamoDbGateway.cs
> +                .ScanAsync(_dynamoDbContext, scanConditions)
We need to evaluate the use of scans on our DynamoDb tables, particularly where we are filtering on more than one property or index, it is a very expensive operation and generally not good practice. We can consider using query vs scan operations or look for an alternative way of querying our DynamoDb tables.

2021-08-12 19:38 UTC, hamidjolany commented on AccountsApi/V1/Gateways/DynamoDbGateway.cs
> +            ScanCondition scanConditionTargetId = new ScanCondition("TargetId", ScanOperator.Equal, targetId);
should we define two global index on these field?

2021-08-13 07:09 UTC, LBHSPreston requested changes
Please complete the details of the pull request comment so it is clear what this pull request covers.  Please include information such as reason for the change, link to any task tickets (JIRA, Clickup, Trello, etc).  It appears that this PR covers a number of tasks.  Moving forward pull requests must be for a single task/ticket unless we are performing a release.

2021-08-24 11:58 UTC, closed without merging